CREATE TABLE companies (
    id BIGSERIAL PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    company_code VARCHAR(50) NOT NULL UNIQUE,
    company_name VARCHAR(255) NOT NULL,
    trade_name VARCHAR(255),
    registration_number VARCHAR(100),
    tax_number VARCHAR(100),
    economic_code VARCHAR(100),
    country_id BIGINT,
    province VARCHAR(100),
    city VARCHAR(100),
    address TEXT,
    postal_code VARCHAR(20),
    phone VARCHAR(50),
    mobile VARCHAR(50),
    email VARCHAR(255),
    website VARCHAR(255),
    logo TEXT,
    default_language VARCHAR(10) DEFAULT 'fa',
    default_currency VARCHAR(10) DEFAULT 'IRR',
    timezone VARCHAR(100) DEFAULT 'Asia/Tehran',
    status SMALLINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted_by BIGINT
);
