// MOLIDO AI — root ESLint flat config.
//
// Scoped to the MVP monorepo. The legacy `backend/` and `web/` directories
// keep their own tooling and are ignored here on purpose.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      '**/*.tsbuildinfo',
      'packages/database/generated/**',
      // Generated by Next on every build; not ours to lint.
      'apps/web/next-env.d.ts',
      // Legacy Molido product — not part of the MVP workspace.
      'backend/**',
      'web/**',
      'legacy/**',
      'n8n-workflows/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx,mts,cts}'],
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      'no-console': ['error', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
    },
  },
  {
    // NestJS relies heavily on decorators + DI; parameter properties and
    // empty interfaces are idiomatic there.
    files: ['apps/api/**/*.ts', 'workers/**/*.ts'],
    rules: {
      '@typescript-eslint/no-extraneous-class': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      // NestJS resolves constructor dependencies from emitted decorator
      // metadata, which requires a *runtime* import. `import type` erases the
      // binding and dependency injection fails at boot with an error that
      // points nowhere useful — so the rule is off wherever DI is in play.
      '@typescript-eslint/consistent-type-imports': 'off',
    },
  },
  {
    // Config files and build scripts run in Node and legitimately print.
    files: ['**/*.config.{js,mjs,cjs,ts}', '**/*.setup.ts', 'infrastructure/**/*.{js,mjs}'],
    languageOptions: {
      globals: {
        process: 'readonly',
        console: 'readonly',
        URL: 'readonly',
        __dirname: 'readonly',
      },
    },
    rules: { 'no-console': 'off' },
  },
  {
    // Seeds and one-off scripts are CLI tools: their output to stdout is the
    // interface, not a stray debug statement.
    files: ['**/prisma/seed.ts', 'infrastructure/scripts/**/*.ts'],
    rules: { 'no-console': 'off' },
  },
);
