// تولیدشده از خودِ پایگاه‌داده با tools/generate-schema.ts — دست نزنید.
//
// ⚠️ پس از هر مهاجرت، `npm run gen:schema` را اجرا کنید.
//
//    `BaseCrudService` ستونی را که این‌جا نباشد بی‌صدا دور می‌ریزد:
//    فرم پر می‌شود، پاسخ ۲۰۰ می‌آید، و میدان خالی می‌ماند.
//    نگهبانِ `npm run check:schema` در CI همین را می‌گیرد.

export const TABLE_COLUMNS: Record<string, readonly string[]> = {
  Account: ['id', 'companyId', 'name', 'code', 'type', 'balance', 'isActive', 'createdAt', 'updatedAt', 'parentId', 'isPostable'],
  AgentCommission: ['id', 'companyId', 'agentId', 'period', 'salesTotal', 'returnTotal', 'netSales', 'rate', 'amount', 'invoiceCount', 'status', 'paidAt', 'note', 'createdAt', 'updatedAt'],
  ApiKey: ['id', 'companyId', 'name', 'keyHash', 'prefix', 'scopes', 'isActive', 'lastUsedAt', 'expiresAt', 'createdAt'],
  Asset: ['id', 'companyId', 'assetNo', 'name', 'category', 'location', 'assignedTo', 'purchaseDate', 'purchasePrice', 'salvageValue', 'usefulLifeYears', 'status', 'description', 'createdAt', 'updatedAt', 'depreciationMethod', 'accumulatedDepreciation', 'inServiceDate', 'disposedAt', 'disposalValue'],
  AssetDepreciation: ['id', 'companyId', 'assetId', 'period', 'amount', 'bookValue', 'journalEntryId', 'createdAt'],
  Attachment: ['id', 'companyId', 'entityType', 'entityId', 'fileName', 'filePath', 'mimeType', 'size', 'createdAt'],
  AttendanceRecord: ['id', 'companyId', 'employeeId', 'date', 'checkIn', 'checkOut', 'workedHours', 'overtimeHours', 'note', 'createdAt', 'updatedAt', 'leaveRequestId', 'status'],
  AuditLog: ['id', 'companyId', 'userId', 'userEmail', 'action', 'entity', 'entityId', 'oldValue', 'newValue', 'ipAddress', 'createdAt'],
  BankReconciliation: ['id', 'companyId', 'accountId', 'statementDate', 'statementBalance', 'status', 'completedAt', 'completedBy', 'note', 'createdAt', 'updatedAt'],
  BankStatementLine: ['id', 'companyId', 'reconciliationId', 'occurredAt', 'amount', 'reference', 'description', 'matchedTxId', 'matchedAt', 'matchMethod', 'createdAt'],
  BarcodeCatalog: ['barcode', 'name', 'brand', 'unit', 'category', 'imageUrl', 'source', 'seenCount', 'createdAt', 'updatedAt'],
  BatchNumber: ['id', 'companyId', 'productId', 'batchNo', 'qty', 'expiryDate', 'manufactureDate', 'createdAt', 'warehouseId', 'purchaseId', 'remainingQty', 'updatedAt'],
  Branch: ['id', 'companyId', 'name', 'code', 'phone', 'email', 'address', 'isActive', 'createdAt', 'updatedAt'],
  Budget: ['id', 'companyId', 'year', 'title', 'department', 'totalAmount', 'spentAmount', 'status', 'description', 'createdAt', 'updatedAt'],
  BudgetCommitment: ['id', 'companyId', 'budgetLineId', 'sourceType', 'sourceId', 'amount', 'status', 'note', 'userId', 'createdAt', 'settledAt'],
  BudgetLine: ['id', 'budgetId', 'title', 'amount', 'spent', 'createdAt', 'updatedAt', 'allocated', 'committed'],
  Cart: ['id', 'companyId', 'customerId', 'guestToken', 'status', 'createdAt', 'updatedAt'],
  CartItem: ['id', 'cartId', 'productId', 'qty', 'priceAtAdd', 'createdAt'],
  CashBox: ['id', 'companyId', 'name', 'code', 'balance', 'createdAt', 'updatedAt'],
  CashBoxTransaction: ['id', 'companyId', 'cashBoxId', 'type', 'amount', 'reason', 'balanceAfter', 'note', 'userId', 'entryId', 'createdAt'],
  CashierShift: ['id', 'companyId', 'userId', 'cashBoxId', 'warehouseId', 'startedAt', 'endedAt', 'openingCash', 'countedCash', 'expectedCash', 'difference', 'salesCount', 'salesTotal', 'cashTotal', 'cardTotal', 'note', 'createdAt', 'updatedAt'],
  Category: ['id', 'companyId', 'name', 'description', 'parentId', 'createdAt', 'updatedAt'],
  Cheque: ['id', 'companyId', 'saleId', 'chequeNo', 'bankName', 'dueDate', 'amount', 'type', 'status', 'ownerName', 'note', 'createdAt', 'updatedAt'],
  ChequePrintTemplate: ['id', 'companyId', 'name', 'bankName', 'widthMm', 'heightMm', 'fields', 'isDefault', 'createdAt', 'updatedAt'],
  CitizenProfile: ['id', 'companyId', 'nationalId', 'firstName', 'lastName', 'phone', 'address', 'createdAt', 'updatedAt'],
  CityAnnouncement: ['id', 'companyId', 'title', 'body', 'category', 'publishedAt', 'isActive', 'createdAt', 'updatedAt'],
  Company: ['id', 'name', 'legalName', 'phone', 'email', 'website', 'country', 'city', 'address', 'taxNumber', 'logo', 'createdAt', 'updatedAt', 'scaleBarcodePrefix', 'scaleBarcodeMode', 'currency', 'currencyDecimals', 'ledgerEnabled', 'maxLineDiscountPercent'],
  Consignment: ['id', 'companyId', 'direction', 'docNo', 'customerId', 'supplierId', 'warehouseId', 'status', 'note', 'userId', 'createdAt', 'updatedAt'],
  ConsignmentItem: ['id', 'companyId', 'consignmentId', 'productId', 'quantity', 'unitPrice', 'unitCost', 'settledQty', 'returnedQty', 'createdAt', 'updatedAt'],
  Contract: ['id', 'companyId', 'contractNo', 'title', 'type', 'status', 'partyName', 'partyPhone', 'partyNationalId', 'amount', 'startDate', 'endDate', 'description', 'createdAt', 'updatedAt'],
  ContractPayment: ['id', 'contractId', 'amount', 'dueDate', 'paidAt', 'status', 'note', 'createdAt'],
  Coupon: ['id', 'companyId', 'code', 'percent', 'amount', 'expiresAt', 'maxUses', 'usedCount', 'isActive', 'createdAt', 'updatedAt'],
  Customer: ['id', 'companyId', 'firstName', 'lastName', 'phone', 'email', 'nationalCode', 'address', 'creditLimit', 'isActive', 'createdAt', 'updatedAt', 'salesAgentId', 'passwordHash', 'emailVerified', 'phoneVerified', 'lastLoginAt', 'priceLevelId', 'smsOptOut', 'smsOptOutAt', 'govSubject', 'personType', 'economicCode', 'postalCode'],
  CustomerAddress: ['id', 'companyId', 'customerId', 'title', 'province', 'city', 'address', 'postalCode', 'receiverName', 'receiverPhone', 'isDefault', 'createdAt', 'updatedAt'],
  CustomerCheckin: ['id', 'companyId', 'customerId', 'token', 'expiresAt', 'usedAt', 'saleId', 'createdAt'],
  CustomerTicket: ['id', 'companyId', 'ticketNo', 'customerId', 'subject', 'category', 'priority', 'status', 'rating', 'resolvedAt', 'createdAt', 'updatedAt'],
  DiscountCampaign: ['id', 'companyId', 'ruleId', 'name', 'segment', 'messageTemplate', 'channel', 'expiresAt', 'sentCount', 'failedCount', 'createdBy', 'createdAt', 'updatedAt'],
  DiscountCode: ['id', 'companyId', 'ruleId', 'campaignId', 'customerId', 'code', 'maxUses', 'usedCount', 'expiresAt', 'sentAt', 'sendError', 'redeemedAt', 'createdAt', 'updatedAt'],
  DiscountRule: ['id', 'companyId', 'name', 'kind', 'value', 'minQty', 'minAmount', 'getQty', 'startsAt', 'endsAt', 'isActive', 'code', 'maxUses', 'usedCount', 'createdAt', 'updatedAt', 'productId', 'categoryId', 'priority', 'requiresCode'],
  EmailCampaign: ['id', 'companyId', 'title', 'subject', 'body', 'status', 'scheduledAt', 'sentAt', 'sentCount', 'openCount', 'clickCount', 'createdAt', 'updatedAt'],
  EmailRecipient: ['id', 'campaignId', 'email', 'name', 'isOpened', 'isClicked'],
  Employee: ['id', 'companyId', 'employeeNo', 'firstName', 'lastName', 'nationalId', 'position', 'department', 'phone', 'hireDate', 'baseSalary', 'housingAllowance', 'foodAllowance', 'isActive', 'note', 'createdAt', 'updatedAt'],
  ErrorGroup: ['id', 'companyId', 'fingerprint', 'message', 'statusCode', 'path', 'method', 'count', 'firstSeenAt', 'lastSeenAt', 'lastStack', 'lastUserId', 'status', 'note', 'createdAt', 'updatedAt'],
  Expense: ['id', 'companyId', 'title', 'amount', 'status', 'note', 'createdAt', 'updatedAt'],
  FiscalYear: ['id', 'companyId', 'code', 'startsOn', 'endsOn', 'status', 'closedAt', 'note', 'createdAt', 'updatedAt'],
  GovSsoState: ['id', 'state', 'nonce', 'codeVerifier', 'audience', 'redirectTo', 'createdAt', 'expiresAt', 'usedAt'],
  HealthCheckLog: ['id', 'companyId', 'service', 'status', 'latencyMs', 'message', 'checkedAt'],
  HealthSnapshot: ['id', 'companyId', 'version', 'metrics', 'severity', 'createdAt'],
  IdempotencyKey: ['id', 'companyId', 'key', 'endpoint', 'response', 'createdAt'],
  Installment: ['id', 'saleId', 'seq', 'dueDate', 'amount', 'status', 'paidAt', 'createdAt', 'updatedAt'],
  Interaction: ['id', 'companyId', 'type', 'subject', 'body', 'leadId', 'opportunityId', 'customerId', 'userId', 'occurredAt', 'followUpAt', 'followUpDone', 'outcome', 'createdAt'],
  Inventory: ['id', 'warehouseId', 'productId', 'quantity', 'createdAt', 'updatedAt', 'avgCost'],
  Investment: ['id', 'companyId', 'title', 'kind', 'principal', 'currentValue', 'returnRate', 'startDate', 'maturityDate', 'status', 'note', 'createdAt', 'updatedAt'],
  JournalEntry: ['id', 'companyId', 'fiscalYearId', 'entryNo', 'entryDate', 'sourceType', 'sourceId', 'description', 'status', 'reversedById', 'createdBy', 'postedAt', 'createdAt', 'updatedAt'],
  JournalLine: ['id', 'entryId', 'accountId', 'lineNo', 'debit', 'credit', 'description', 'createdAt'],
  JournalTemplate: ['id', 'companyId', 'title', 'description', 'lines', 'frequency', 'nextRunOn', 'lastRunOn', 'isActive', 'createdBy', 'createdAt', 'updatedAt'],
  Lead: ['id', 'companyId', 'leadNo', 'name', 'company', 'phone', 'email', 'source', 'status', 'score', 'assignedTo', 'salesAgentId', 'customerId', 'note', 'createdAt', 'updatedAt'],
  LeaveBalance: ['id', 'companyId', 'employeeId', 'year', 'kind', 'entitled', 'used', 'carriedOver', 'createdAt', 'updatedAt'],
  LeaveRequest: ['id', 'companyId', 'employeeId', 'kind', 'startDate', 'endDate', 'days', 'reason', 'status', 'decidedAt', 'createdAt', 'updatedAt', 'decidedBy', 'decisionNote'],
  Loan: ['id', 'companyId', 'loanNo', 'borrowerName', 'borrowerType', 'borrowerId', 'amount', 'interestRate', 'months', 'startDate', 'status', 'createdAt', 'updatedAt'],
  LoanRepayment: ['id', 'loanId', 'dueDate', 'amount', 'paidAt', 'isPaid'],
  LoginAttempt: ['id', 'email', 'ip', 'userAgent', 'success', 'reason', 'createdAt'],
  LoyaltyAccount: ['id', 'companyId', 'customerId', 'points', 'tier', 'note', 'createdAt', 'updatedAt'],
  MenuCategory: ['id', 'companyId', 'name', 'nameEn', 'nameAr', 'sortOrder', 'icon', 'isActive', 'createdAt', 'updatedAt'],
  MenuItem: ['id', 'companyId', 'categoryId', 'code', 'name', 'nameEn', 'nameAr', 'description', 'imageUrl', 'price', 'cost', 'taxRate', 'station', 'prepMinutes', 'calories', 'isAvailable', 'isSpicy', 'isVegan', 'sortOrder', 'createdAt', 'updatedAt'],
  MenuRecipe: ['id', 'menuItemId', 'productId', 'qty', 'unit', 'wastePct'],
  MfaRecoveryCode: ['id', 'userId', 'codeHash', 'usedAt', 'createdAt'],
  NewsPost: ['id', 'companyId', 'title', 'body', 'category', 'imageUrl', 'status', 'publishedAt', 'authorName', 'viewCount', 'createdAt', 'updatedAt'],
  OnlineOrder: ['id', 'companyId', 'orderNo', 'customerId', 'addressId', 'shipAddress', 'receiverName', 'receiverPhone', 'subtotal', 'discount', 'shippingFee', 'tax', 'total', 'paymentMethod', 'paymentStatus', 'paymentRef', 'status', 'salesOrderId', 'note', 'placedAt', 'confirmedAt', 'cancelledAt', 'createdAt', 'updatedAt'],
  OnlineOrderItem: ['id', 'orderId', 'productId', 'name', 'qty', 'unitPrice', 'total'],
  Opportunity: ['id', 'companyId', 'oppNo', 'title', 'leadId', 'customerId', 'salesAgentId', 'assignedTo', 'amount', 'probability', 'stage', 'expectedCloseDate', 'closedAt', 'lostReason', 'quotationId', 'note', 'createdAt', 'updatedAt'],
  ParkedSale: ['id', 'companyId', 'userId', 'shiftId', 'label', 'customerId', 'lines', 'note', 'createdAt', 'updatedAt'],
  Payment: ['id', 'saleId', 'cashBoxId', 'method', 'status', 'amount', 'referenceNo', 'note', 'createdAt', 'updatedAt'],
  PayrollSlip: ['id', 'companyId', 'employeeId', 'period', 'baseSalary', 'allowances', 'overtimeHours', 'overtimePay', 'bonus', 'deductions', 'insurance', 'tax', 'netPay', 'status', 'paidAt', 'note', 'createdAt', 'updatedAt', 'journalEntryId', 'paymentMethod', 'leaveDays', 'absentDays'],
  PerformanceReview: ['id', 'companyId', 'employeeId', 'period', 'score', 'strengths', 'weaknesses', 'reviewerName', 'suggestedBonus', 'note', 'createdAt', 'updatedAt'],
  PettyCash: ['id', 'companyId', 'name', 'custodianId', 'ceiling', 'isActive', 'note', 'createdAt', 'updatedAt'],
  PettyCashTransaction: ['id', 'companyId', 'pettyCashId', 'type', 'amount', 'description', 'entryId', 'userId', 'occurredAt', 'createdAt'],
  PhoneVerification: ['id', 'companyId', 'phone', 'codeHash', 'attempts', 'expiresAt', 'consumedAt', 'createdAt'],
  PlanDefault: ['plan', 'title', 'maxUsers', 'maxBranches', 'note', 'features', 'priceRial'],
  PosTerminal: ['id', 'companyId', 'terminalNo', 'serialNo', 'merchantId', 'bankName', 'pspName', 'type', 'status', 'accountNo', 'iban', 'holderName', 'location', 'simNumber', 'cashBoxId', 'installedAt', 'note', 'createdAt', 'updatedAt'],
  PriceLevel: ['id', 'companyId', 'name', 'description', 'isDefault', 'createdAt'],
  Product: ['id', 'companyId', 'categoryId', 'name', 'sku', 'barcode', 'description', 'purchasePrice', 'salePrice', 'taxRate', 'unit', 'status', 'trackInventory', 'minStock', 'expiryDate', 'createdAt', 'updatedAt', 'isWeighed', 'scaleCode', 'isRationEligible', 'rationPrice', 'isOnline', 'onlinePrice', 'imageUrl'],
  ProductPrice: ['id', 'priceLevelId', 'productId', 'price', 'createdAt', 'companyId', 'minQty', 'updatedAt'],
  ProductReturn: ['id', 'companyId', 'returnNo', 'saleId', 'customerId', 'reason', 'status', 'totalAmount', 'note', 'createdAt', 'updatedAt', 'type', 'purchaseId', 'supplierId', 'warehouseId', 'refundMethod', 'refundAmount', 'cashBoxId', 'userId', 'appliedAt'],
  ProductReturnItem: ['id', 'returnId', 'productId', 'name', 'qty', 'unitPrice', 'total', 'sourceItemId'],
  ProductReview: ['id', 'companyId', 'productId', 'customerId', 'rating', 'comment', 'approved', 'createdAt', 'updatedAt'],
  ProductVariant: ['id', 'productId', 'name', 'sku', 'barcode', 'price', 'createdAt', 'updatedAt'],
  Purchase: ['id', 'companyId', 'supplierId', 'warehouseId', 'purchaseNo', 'status', 'subtotal', 'discount', 'tax', 'total', 'note', 'createdAt', 'updatedAt', 'freightCost', 'freightCarrier', 'capitalizeFreight'],
  PurchaseInquiry: ['id', 'companyId', 'inquiryNo', 'title', 'status', 'warehouseId', 'note', 'purchaseId', 'createdBy', 'createdAt', 'updatedAt'],
  PurchaseInquiryItem: ['id', 'inquiryId', 'productId', 'qty', 'lastPrice'],
  PurchaseItem: ['id', 'purchaseId', 'productId', 'quantity', 'purchasePrice', 'total', 'createdAt', 'returnedQty', 'batchNo', 'expiryDate', 'manufactureDate', 'freightShare', 'landedUnitCost'],
  QuickKey: ['id', 'companyId', 'groupId', 'productId', 'label', 'color', 'defaultQty', 'sortOrder', 'createdAt', 'updatedAt'],
  QuickKeyGroup: ['id', 'companyId', 'name', 'color', 'sortOrder', 'isActive', 'createdAt', 'updatedAt'],
  Quotation: ['id', 'companyId', 'quoteNo', 'customerId', 'validUntil', 'status', 'totalAmount', 'discount', 'tax', 'note', 'createdAt', 'updatedAt', 'salesOrderId'],
  QuotationItem: ['id', 'quotationId', 'productId', 'name', 'qty', 'unitPrice', 'total'],
  RationAccount: ['id', 'companyId', 'nationalCode', 'holderName', 'phone', 'householdSize', 'balance', 'periodCode', 'isActive', 'note', 'createdAt', 'updatedAt'],
  RationTransaction: ['id', 'companyId', 'accountId', 'type', 'amount', 'saleId', 'periodCode', 'reference', 'note', 'createdAt'],
  Receipt: ['id', 'companyId', 'receiptNo', 'entityType', 'entityId', 'amount', 'method', 'cashBoxId', 'treasuryAccountId', 'payerName', 'reference', 'note', 'paidAt', 'createdAt'],
  Reminder: ['id', 'companyId', 'title', 'note', 'dueAt', 'status', 'doneAt', 'assignedTo', 'createdBy', 'entityType', 'entityId', 'createdAt', 'updatedAt'],
  ReportDefinition: ['id', 'companyId', 'name', 'description', 'dataset', 'spec', 'isShared', 'createdBy', 'createdAt', 'updatedAt'],
  RestaurantArea: ['id', 'companyId', 'name', 'floor', 'isSmoking', 'isOutdoor', 'isActive', 'createdAt', 'updatedAt'],
  RestaurantOrder: ['id', 'companyId', 'orderNo', 'type', 'status', 'tableId', 'customerId', 'waiterId', 'guestCount', 'subtotal', 'discount', 'serviceCharge', 'tax', 'total', 'paidAmount', 'tipAmount', 'paymentMethod', 'deliveryAddress', 'deliveryPhone', 'deliveryFee', 'courierName', 'saleId', 'note', 'openedAt', 'kitchenAt', 'closedAt', 'createdAt', 'updatedAt', 'source', 'guestPhone', 'guestCode', 'shiftId', 'paymentRef', 'bankRef', 'paidAt'],
  RestaurantOrderItem: ['id', 'orderId', 'menuItemId', 'name', 'qty', 'unitPrice', 'discount', 'total', 'status', 'station', 'note', 'sentAt', 'readyAt', 'servedAt', 'createdAt', 'unitCost'],
  RestaurantShift: ['id', 'companyId', 'userId', 'startedAt', 'endedAt', 'openingCash', 'closingCash', 'totalSales', 'tipsAmount', 'ordersCount', 'note', 'createdAt'],
  RestaurantTable: ['id', 'companyId', 'areaId', 'tableNo', 'capacity', 'status', 'qrCode', 'note', 'createdAt', 'updatedAt', 'qrToken'],
  RolePermission: ['id', 'companyId', 'role', 'permission', 'allowed', 'updatedBy', 'createdAt', 'updatedAt'],
  Sale: ['id', 'companyId', 'customerId', 'userId', 'warehouseId', 'invoiceNo', 'status', 'subtotal', 'discount', 'tax', 'total', 'note', 'createdAt', 'updatedAt', 'shiftId', 'rationAccountId', 'rationAmount', 'salesAgentId', 'freightCharge', 'freightCost', 'discountCodeId', 'taxInvoiceId', 'discountBy', 'reference', 'dueDate', 'additions', 'deductions', 'invoiceDate', 'agentCommission'],
  SaleItem: ['id', 'saleId', 'productId', 'quantity', 'price', 'discount', 'total', 'createdAt', 'returnedQty', 'manualDiscount', 'note', 'taxRate', 'taxAmount', 'serial', 'unitCost', 'consignmentItemId'],
  SalesAgent: ['id', 'companyId', 'name', 'phone', 'territory', 'commissionRate', 'monthlyTarget', 'isActive', 'createdAt', 'updatedAt', 'agentNo', 'userId', 'nationalCode'],
  SalesOrder: ['id', 'companyId', 'orderNo', 'customerId', 'status', 'totalAmount', 'note', 'createdAt', 'updatedAt', 'quotationId', 'saleId', 'warehouseId', 'discount', 'tax'],
  SalesOrderItem: ['id', 'orderId', 'productId', 'name', 'qty', 'unitPrice', 'total', 'shippedQty'],
  SelfOrderSetting: ['companyId', 'menuEnabled', 'orderEnabled', 'requireApproval', 'requirePrepay', 'servicePercent', 'taxPercent', 'maxOrderAmount', 'welcomeText', 'createdAt', 'updatedAt'],
  SerialNumber: ['id', 'companyId', 'productId', 'serial', 'status', 'saleId', 'createdAt', 'warrantyUntil', 'note', 'updatedAt'],
  ShahkarVerification: ['id', 'companyId', 'nationalCode', 'mobile', 'outcome', 'reference', 'provider', 'checkedAt', 'createdAt', 'updatedAt'],
  Shipment: ['id', 'companyId', 'trackingNo', 'saleId', 'carrier', 'method', 'fee', 'estimatedAt', 'deliveredAt', 'status', 'address', 'note', 'createdAt', 'updatedAt', 'salesOrderId', 'carrierCost', 'journalEntryId'],
  ShipmentItem: ['id', 'shipmentId', 'productId', 'name', 'qty'],
  ShopSetting: ['companyId', 'shopName', 'shopDescription', 'isOpen', 'shippingFee', 'freeShippingOver', 'minOrderAmount', 'warehouseId', 'supportPhone', 'createdAt', 'updatedAt'],
  SiteModule: ['id', 'companyId', 'slug', 'title', 'summary', 'priceIrr', 'isActive', 'sortOrder', 'createdAt', 'updatedAt'],
  SitePurchase: ['id', 'companyId', 'trackingCode', 'buyerName', 'buyerPhone', 'buyerEmail', 'buyerCompany', 'note', 'items', 'amountIrr', 'status', 'paymentRef', 'bankRef', 'paidAt', 'leadId', 'createdAt', 'updatedAt'],
  SmsMessage: ['id', 'companyId', 'phone', 'customerId', 'body', 'status', 'skipReason', 'error', 'providerId', 'cost', 'kind', 'campaignId', 'dedupeKey', 'sentAt', 'createdAt'],
  SmsTemplate: ['id', 'companyId', 'name', 'body', 'isActive', 'createdAt', 'updatedAt'],
  StockCount: ['id', 'companyId', 'warehouseId', 'countNo', 'status', 'note', 'userId', 'appliedAt', 'createdAt', 'updatedAt'],
  StockCountLine: ['id', 'countId', 'productId', 'systemQty', 'countedQty', 'note'],
  StockMovement: ['id', 'companyId', 'warehouseId', 'productId', 'delta', 'balance', 'reason', 'refType', 'refId', 'userId', 'note', 'createdAt'],
  Subscription: ['id', 'companyId', 'plan', 'status', 'startsOn', 'endsOn', 'maxUsers', 'maxBranches', 'product', 'note', 'createdAt', 'updatedAt'],
  SubscriptionInvoice: ['id', 'companyId', 'plan', 'months', 'amountRial', 'status', 'gateway', 'reference', 'trackingCode', 'paidAt', 'note', 'createdAt', 'updatedAt'],
  Supplier: ['id', 'companyId', 'name', 'phone', 'email', 'address', 'isActive', 'createdAt', 'updatedAt', 'nationalCode', 'personType', 'economicCode', 'postalCode'],
  SupplierCall: ['id', 'companyId', 'inquiryId', 'supplierId', 'status', 'channel', 'phone', 'providerId', 'recordingUrl', 'transcript', 'durationSec', 'error', 'note', 'calledAt', 'createdAt', 'updatedAt'],
  SupplierQuote: ['id', 'companyId', 'callId', 'productId', 'unitPrice', 'availableQty', 'leadDays', 'note', 'isSelected', 'createdAt'],
  SupportSession: ['id', 'companyId', 'code', 'scope', 'grantedBy', 'reason', 'expiresAt', 'usedAt', 'revokedAt', 'supportName', 'createdAt'],
  Survey: ['id', 'companyId', 'title', 'description', 'isActive', 'createdAt', 'updatedAt'],
  SurveyAnswer: ['id', 'questionId', 'responseId', 'value'],
  SurveyQuestion: ['id', 'surveyId', 'text', 'qtype', 'options', 'sortOrder'],
  SurveyResponse: ['id', 'surveyId', 'respondentName', 'submittedAt'],
  TableReservation: ['id', 'companyId', 'tableId', 'customerName', 'phone', 'guests', 'reservedAt', 'durationMin', 'status', 'note', 'createdAt', 'updatedAt'],
  TaxInvoice: ['id', 'companyId', 'saleId', 'taxId', 'status', 'referenceNo', 'attempts', 'lastError', 'payload', 'sentAt', 'confirmedAt', 'createdAt', 'updatedAt'],
  TaxInvoiceLog: ['id', 'companyId', 'taxInvoiceId', 'action', 'httpStatus', 'response', 'createdAt'],
  TaxSetting: ['companyId', 'memoryId', 'economicCode', 'apiBaseUrl', 'privateKeyPem', 'clientId', 'serial', 'isEnabled', 'isSandbox', 'createdAt', 'updatedAt'],
  Tender: ['id', 'companyId', 'tenderNo', 'title', 'kind', 'baseAmount', 'deadline', 'status', 'winnerBidId', 'description', 'createdAt', 'updatedAt'],
  TenderBid: ['id', 'tenderId', 'bidderName', 'bidderPhone', 'amount', 'notes', 'createdAt'],
  TicketMessage: ['id', 'ticketId', 'body', 'isAgent', 'senderName', 'createdAt'],
  TrainingCourse: ['id', 'companyId', 'title', 'instructor', 'hours', 'startDate', 'endDate', 'isActive', 'createdAt', 'updatedAt'],
  TrainingEnrollment: ['id', 'courseId', 'employeeId', 'score', 'passed', 'certUrl', 'createdAt'],
  TreasuryAccount: ['id', 'companyId', 'name', 'type', 'bankName', 'accountNo', 'iban', 'balance', 'isActive', 'note', 'createdAt', 'updatedAt'],
  TreasuryTransaction: ['id', 'companyId', 'accountId', 'type', 'amount', 'reference', 'description', 'date', 'createdAt'],
  User: ['id', 'firstName', 'lastName', 'email', 'phone', 'password', 'role', 'status', 'avatar', 'companyId', 'createdAt', 'updatedAt', 'passwordChangedAt', 'lockedUntil', 'sessionsRevokedAt', 'mfaSecret', 'mfaEnabledAt', 'govSubject', 'nationalCode'],
  VoicePhrase: ['id', 'companyId', 'lang', 'dialect', 'kind', 'productId', 'textFa', 'textTarget', 'sortOrder', 'createdAt', 'source'],
  VoiceSample: ['id', 'companyId', 'phraseId', 'audioUrl', 'durationMs', 'sizeBytes', 'speakerTag', 'status', 'rejectReason', 'recordedBy', 'createdAt'],
  VoipSetting: ['companyId', 'provider', 'isEnabled', 'callerId', 'apiKey', 'webhookSecret', 'maxCallsPerRun', 'createdAt', 'updatedAt'],
  Warehouse: ['id', 'companyId', 'branchId', 'name', 'code', 'description', 'createdAt', 'updatedAt'],
  Webhook: ['id', 'companyId', 'name', 'kind', 'url', 'secret', 'isActive', 'createdAt', 'updatedAt'],
  WebhookLog: ['id', 'webhookId', 'payload', 'status', 'sentAt'],
};
