// Generated from prisma/schema.prisma by tools/generate-schema.ts.
// Column whitelist used by CrudRepository to build parameterised SQL.

export const TABLE_COLUMNS: Record<string, readonly string[]> = {
  Account: ['id', 'companyId', 'name', 'code', 'type', 'balance', 'isActive', 'parentId', 'isPostable', 'createdAt', 'updatedAt'],
  ApiKey: ['id', 'companyId', 'name', 'keyHash', 'prefix', 'scopes', 'isActive', 'lastUsedAt', 'expiresAt', 'createdAt'],
  Appointment: ['id', 'companyId', 'serviceUnit', 'customerId', 'appointmentDate', 'slot', 'status', 'note', 'createdAt', 'updatedAt'],
  ApprovalRequest: ['id', 'companyId', 'entityType', 'entityId', 'title', 'amount', 'requestedBy', 'currentStep', 'status', 'createdAt', 'updatedAt'],
  ApprovalStep: ['id', 'requestId', 'stepNo', 'approverRole', 'status', 'comment', 'decidedAt', 'createdAt'],
  Asset: ['id', 'companyId', 'assetNo', 'name', 'category', 'location', 'assignedTo', 'purchaseDate', 'purchasePrice', 'salvageValue', 'usefulLifeYears', 'status', 'description', 'createdAt', 'updatedAt', 'depreciationMethod', 'accumulatedDepreciation', 'inServiceDate', 'disposedAt', 'disposalValue'],
  AssetDepreciation: ['id', 'companyId', 'assetId', 'period', 'amount', 'bookValue', 'journalEntryId', 'createdAt'],
  Attachment: ['id', 'companyId', 'entityType', 'entityId', 'fileName', 'filePath', 'mimeType', 'size', 'createdAt'],
  AttendanceRecord: ['id', 'companyId', 'employeeId', 'date', 'checkIn', 'checkOut', 'workedHours', 'overtimeHours', 'note', 'createdAt', 'updatedAt', 'leaveRequestId', 'status'],
  AuditLog: ['id', 'companyId', 'userId', 'userEmail', 'action', 'entity', 'entityId', 'oldValue', 'newValue', 'ipAddress', 'createdAt'],
  BatchNumber: ['id', 'companyId', 'productId', 'batchNo', 'qty', 'expiryDate', 'manufactureDate', 'createdAt', 'warehouseId', 'purchaseId', 'remainingQty', 'updatedAt'],
  Branch: ['id', 'companyId', 'name', 'code', 'phone', 'email', 'address', 'isActive', 'createdAt', 'updatedAt'],
  Budget: ['id', 'companyId', 'year', 'title', 'department', 'totalAmount', 'spentAmount', 'status', 'description', 'createdAt', 'updatedAt'],
  BudgetLine: ['id', 'budgetId', 'title', 'amount', 'spent', 'createdAt', 'updatedAt'],
  BuildingPermit: ['id', 'companyId', 'permitNo', 'type', 'status', 'ownerName', 'ownerPhone', 'nationalCode', 'address', 'plateNumber', 'area', 'floors', 'description', 'rejectReason', 'issuedAt', 'expiresAt', 'createdAt', 'updatedAt'],
  BuildingViolation: ['id', 'companyId', 'caseNo', 'ownerName', 'address', 'description', 'status', 'fineAmount', 'createdAt', 'updatedAt'],
  BurialPermit: ['id', 'companyId', 'cemeteryId', 'permitNo', 'deceasedName', 'issueDate', 'fee', 'note', 'createdAt'],
  BusinessLicense: ['id', 'companyId', 'licenseNo', 'businessName', 'ownerName', 'phone', 'address', 'businessType', 'issueDate', 'expiryDate', 'annualFee', 'status', 'createdAt', 'updatedAt'],
  CashBox: ['id', 'companyId', 'name', 'code', 'balance', 'createdAt', 'updatedAt'],
  CashierShift: ['id', 'companyId', 'userId', 'cashBoxId', 'warehouseId', 'startedAt', 'endedAt', 'openingCash', 'countedCash', 'expectedCash', 'difference', 'salesCount', 'salesTotal', 'cashTotal', 'cardTotal', 'note', 'createdAt', 'updatedAt'],
  Category: ['id', 'companyId', 'name', 'description', 'parentId', 'createdAt', 'updatedAt'],
  CctvCamera: ['id', 'companyId', 'cameraCode', 'location', 'zone', 'streamUrl', 'status', 'installDate', 'createdAt', 'updatedAt'],
  CctvReport: ['id', 'cameraId', 'fault', 'isDone', 'fixedAt', 'createdAt'],
  Cemetery: ['id', 'companyId', 'name', 'location', 'capacity', 'createdAt', 'updatedAt'],
  Cheque: ['id', 'companyId', 'saleId', 'chequeNo', 'bankName', 'dueDate', 'amount', 'type', 'status', 'ownerName', 'note', 'createdAt', 'updatedAt'],
  CitizenComplaint: ['id', 'companyId', 'trackingNo', 'category', 'status', 'citizenName', 'citizenPhone', 'address', 'subject', 'description', 'referredTo', 'responseNote', 'createdAt', 'updatedAt'],
  CitizenProfile: ['id', 'companyId', 'nationalId', 'firstName', 'lastName', 'phone', 'address', 'createdAt', 'updatedAt'],
  CityAnnouncement: ['id', 'companyId', 'title', 'body', 'category', 'publishedAt', 'isActive', 'createdAt', 'updatedAt'],
  CityServiceRequest: ['id', 'companyId', 'trackingCode', 'citizenId', 'serviceType', 'subject', 'details', 'status', 'assignedTo', 'response', 'answeredAt', 'createdAt', 'updatedAt'],
  ClinicRecord: ['id', 'companyId', 'employeeId', 'patientName', 'visitDate', 'visitType', 'diagnosis', 'prescription', 'doctorName', 'cost', 'note', 'createdAt', 'updatedAt'],
  Company: ['id', 'name', 'legalName', 'phone', 'email', 'website', 'country', 'city', 'address', 'taxNumber', 'logo', 'createdAt', 'updatedAt', 'scaleBarcodePrefix', 'scaleBarcodeMode', 'currency', 'currencyDecimals', 'ledgerEnabled', 'maxLineDiscountPercent'],
  ConstructionProject: ['id', 'companyId', 'projectNo', 'title', 'contractorName', 'location', 'budgetAmount', 'physicalProgress', 'financialProgress', 'startDate', 'endDate', 'status', 'description', 'createdAt', 'updatedAt'],
  Contract: ['id', 'companyId', 'contractNo', 'title', 'type', 'status', 'partyName', 'partyPhone', 'partyNationalId', 'amount', 'startDate', 'endDate', 'description', 'createdAt', 'updatedAt'],
  ContractPayment: ['id', 'contractId', 'amount', 'dueDate', 'paidAt', 'status', 'note', 'createdAt'],
  CouncilDecision: ['id', 'meetingId', 'decisionNo', 'subject', 'content', 'isDone', 'deadline', 'createdAt'],
  CouncilMeeting: ['id', 'companyId', 'title', 'meetingDate', 'location', 'status', 'agenda', 'createdAt', 'updatedAt'],
  Coupon: ['id', 'companyId', 'code', 'percent', 'amount', 'expiresAt', 'maxUses', 'usedCount', 'isActive', 'createdAt', 'updatedAt'],
  CrisisAction: ['id', 'eventId', 'actionDate', 'description', 'responsibleTeam', 'isDone', 'createdAt'],
  CrisisEvent: ['id', 'companyId', 'title', 'crisisType', 'location', 'severity', 'status', 'reportedAt', 'resolvedAt', 'description', 'casualties', 'createdAt', 'updatedAt'],
  Cart: ['id', 'companyId', 'customerId', 'guestToken', 'status', 'createdAt', 'updatedAt'],
  CartItem: ['id', 'cartId', 'productId', 'qty', 'priceAtAdd', 'createdAt'],
  CustomerAddress: ['id', 'companyId', 'customerId', 'title', 'province', 'city', 'address', 'postalCode', 'receiverName', 'receiverPhone', 'isDefault', 'createdAt', 'updatedAt'],
  CustomerCheckin: ['id', 'companyId', 'customerId', 'token', 'expiresAt', 'usedAt', 'saleId', 'createdAt'],
  DiscountCampaign: ['id', 'companyId', 'ruleId', 'name', 'segment', 'messageTemplate', 'channel', 'expiresAt', 'sentCount', 'failedCount', 'createdBy', 'createdAt', 'updatedAt'],
  DiscountCode: ['id', 'companyId', 'ruleId', 'campaignId', 'customerId', 'code', 'maxUses', 'usedCount', 'expiresAt', 'sentAt', 'sendError', 'redeemedAt', 'createdAt', 'updatedAt'],
  ErrorGroup: ['id', 'companyId', 'fingerprint', 'message', 'statusCode', 'path', 'method', 'count', 'firstSeenAt', 'lastSeenAt', 'lastStack', 'lastUserId', 'status', 'note', 'createdAt', 'updatedAt'],
  HealthSnapshot: ['id', 'companyId', 'version', 'metrics', 'severity', 'createdAt'],
  LeaveBalance: ['id', 'companyId', 'employeeId', 'year', 'kind', 'entitled', 'used', 'carriedOver', 'createdAt', 'updatedAt'],
  OnlineOrder: ['id', 'companyId', 'orderNo', 'customerId', 'addressId', 'shipAddress', 'receiverName', 'receiverPhone', 'subtotal', 'discount', 'shippingFee', 'tax', 'total', 'paymentMethod', 'paymentStatus', 'paymentRef', 'status', 'salesOrderId', 'note', 'placedAt', 'confirmedAt', 'cancelledAt', 'createdAt', 'updatedAt'],
  OnlineOrderItem: ['id', 'orderId', 'productId', 'name', 'qty', 'unitPrice', 'total'],
  ParkedSale: ['id', 'companyId', 'userId', 'shiftId', 'label', 'customerId', 'lines', 'note', 'createdAt', 'updatedAt'],
  ShopSetting: ['companyId', 'shopName', 'shopDescription', 'isOpen', 'shippingFee', 'freeShippingOver', 'minOrderAmount', 'warehouseId', 'supportPhone', 'createdAt', 'updatedAt'],
  Customer: ['id', 'companyId', 'firstName', 'lastName', 'phone', 'email', 'nationalCode', 'address', 'creditLimit', 'isActive', 'createdAt', 'updatedAt', 'salesAgentId', 'passwordHash', 'emailVerified', 'phoneVerified', 'lastLoginAt', 'priceLevelId', 'smsOptOut', 'smsOptOutAt'],
  CustomerTicket: ['id', 'companyId', 'ticketNo', 'customerId', 'subject', 'category', 'priority', 'status', 'rating', 'resolvedAt', 'createdAt', 'updatedAt'],
  DiscountRule: ['id', 'companyId', 'name', 'kind', 'value', 'minQty', 'minAmount', 'getQty', 'startsAt', 'endsAt', 'isActive', 'code', 'maxUses', 'usedCount', 'createdAt', 'updatedAt', 'productId', 'categoryId', 'priority', 'requiresCode'],
  Document: ['id', 'folderId', 'title', 'fileUrl', 'version', 'tags', 'uploadedBy', 'createdAt', 'updatedAt'],
  DocumentFolder: ['id', 'companyId', 'name', 'parentId', 'createdAt'],
  EmailCampaign: ['id', 'companyId', 'title', 'subject', 'body', 'status', 'scheduledAt', 'sentAt', 'sentCount', 'openCount', 'clickCount', 'createdAt', 'updatedAt'],
  EmailRecipient: ['id', 'campaignId', 'email', 'name', 'isOpened', 'isClicked'],
  Employee: ['id', 'companyId', 'employeeNo', 'firstName', 'lastName', 'nationalId', 'position', 'department', 'phone', 'hireDate', 'baseSalary', 'housingAllowance', 'foodAllowance', 'isActive', 'note', 'createdAt', 'updatedAt'],
  Expense: ['id', 'companyId', 'title', 'amount', 'status', 'note', 'createdAt', 'updatedAt'],
  FireFighter: ['id', 'stationId', 'firstName', 'lastName', 'rank', 'phone', 'nationalCode', 'isOnDuty', 'isActive', 'createdAt', 'updatedAt'],
  FireIncident: ['id', 'companyId', 'stationId', 'incidentNo', 'type', 'status', 'address', 'reporterName', 'reporterPhone', 'description', 'casualties', 'injuries', 'reportedAt', 'dispatchedAt', 'resolvedAt', 'createdAt', 'updatedAt'],
  FireStation: ['id', 'companyId', 'name', 'code', 'address', 'phone', 'createdAt', 'updatedAt'],
  FireVehicle: ['id', 'stationId', 'name', 'plateNo', 'vehicleType', 'status', 'createdAt', 'updatedAt'],
  FiscalYear: ['id', 'companyId', 'code', 'startsOn', 'endsOn', 'status', 'closedAt', 'note', 'createdAt', 'updatedAt'],
  FleetFuelLog: ['id', 'vehicleId', 'date', 'liters', 'cost', 'odometer', 'createdAt'],
  FleetService: ['id', 'vehicleId', 'date', 'serviceType', 'cost', 'description', 'createdAt'],
  FleetVehicle: ['id', 'companyId', 'plateNo', 'name', 'vehicleType', 'modelYear', 'driverName', 'insuranceExpiry', 'inspectionExpiry', 'status', 'note', 'createdAt', 'updatedAt'],
  Grave: ['id', 'cemeteryId', 'section', 'row', 'number', 'deceasedName', 'buriedAt', 'isOccupied', 'createdAt'],
  GuildInspection: ['id', 'licenseId', 'date', 'inspector', 'result', 'note', 'createdAt'],
  HealthCheckLog: ['id', 'companyId', 'service', 'status', 'latencyMs', 'message', 'checkedAt'],
  HelpTicket: ['id', 'companyId', 'ticketNo', 'category', 'subject', 'description', 'priority', 'status', 'assignedToId', 'slaHours', 'resolvedAt', 'createdAt', 'updatedAt'],
  Installment: ['id', 'saleId', 'seq', 'dueDate', 'amount', 'status', 'paidAt', 'createdAt', 'updatedAt'],
  Inventory: ['id', 'warehouseId', 'productId', 'quantity', 'createdAt', 'updatedAt'],
  Investment: ['id', 'companyId', 'title', 'kind', 'principal', 'currentValue', 'returnRate', 'startDate', 'maturityDate', 'status', 'note', 'createdAt', 'updatedAt'],
  IotSensor: ['id', 'companyId', 'sensorCode', 'name', 'kind', 'location', 'lat', 'lng', 'status', 'threshold', 'createdAt', 'updatedAt'],
  JournalEntry: ['id', 'companyId', 'fiscalYearId', 'entryNo', 'entryDate', 'sourceType', 'sourceId', 'description', 'status', 'reversedById', 'createdBy', 'postedAt', 'createdAt', 'updatedAt'],
  JournalLine: ['id', 'entryId', 'accountId', 'lineNo', 'debit', 'credit', 'description', 'createdAt'],
  LeaveRequest: ['id', 'companyId', 'employeeId', 'kind', 'startDate', 'endDate', 'days', 'reason', 'status', 'decidedAt', 'createdAt', 'updatedAt', 'decidedBy', 'decisionNote'],
  Letter: ['id', 'companyId', 'indicatorNo', 'direction', 'subject', 'fromEntity', 'toEntity', 'letterDate', 'referredTo', 'status', 'fileUrl', 'description', 'createdAt', 'updatedAt'],
  Loan: ['id', 'companyId', 'loanNo', 'borrowerName', 'borrowerType', 'borrowerId', 'amount', 'interestRate', 'months', 'startDate', 'status', 'createdAt', 'updatedAt'],
  LoanRepayment: ['id', 'loanId', 'dueDate', 'amount', 'paidAt', 'isPaid'],
  Interaction: ['id', 'companyId', 'type', 'subject', 'body', 'leadId', 'opportunityId', 'customerId', 'userId', 'occurredAt', 'followUpAt', 'followUpDone', 'outcome', 'createdAt'],
  Lead: ['id', 'companyId', 'leadNo', 'name', 'company', 'phone', 'email', 'source', 'status', 'score', 'assignedTo', 'salesAgentId', 'customerId', 'note', 'createdAt', 'updatedAt'],
  Opportunity: ['id', 'companyId', 'oppNo', 'title', 'leadId', 'customerId', 'salesAgentId', 'assignedTo', 'amount', 'probability', 'stage', 'expectedCloseDate', 'closedAt', 'lostReason', 'quotationId', 'note', 'createdAt', 'updatedAt'],
  LoyaltyAccount: ['id', 'companyId', 'customerId', 'points', 'tier', 'note', 'createdAt', 'updatedAt'],
  MenuCategory: ['id', 'companyId', 'name', 'nameEn', 'nameAr', 'sortOrder', 'icon', 'isActive', 'createdAt', 'updatedAt'],
  MenuItem: ['id', 'companyId', 'categoryId', 'code', 'name', 'nameEn', 'nameAr', 'description', 'imageUrl', 'price', 'cost', 'taxRate', 'station', 'prepMinutes', 'calories', 'isAvailable', 'isSpicy', 'isVegan', 'sortOrder', 'createdAt', 'updatedAt'],
  MenuRecipe: ['id', 'menuItemId', 'productId', 'qty', 'unit', 'wastePct'],
  MunicipalBill: ['id', 'companyId', 'billNo', 'type', 'status', 'payerName', 'payerPhone', 'address', 'amount', 'description', 'permitId', 'paidAt', 'createdAt', 'updatedAt'],
  MunicipalProperty: ['id', 'companyId', 'propNo', 'name', 'address', 'areaSqm', 'status', 'monthlyRent', 'tenantName', 'leaseExpiry', 'note', 'createdAt', 'updatedAt'],
  NewsPost: ['id', 'companyId', 'title', 'body', 'category', 'imageUrl', 'status', 'publishedAt', 'authorName', 'viewCount', 'createdAt', 'updatedAt'],
  ParkingLot: ['id', 'companyId', 'name', 'address', 'capacity', 'hourlyRate', 'isActive', 'createdAt', 'updatedAt'],
  ParkingSession: ['id', 'lotId', 'plateNo', 'enteredAt', 'exitedAt', 'fee', 'isPaid', 'createdAt'],
  Payment: ['id', 'saleId', 'cashBoxId', 'method', 'status', 'amount', 'referenceNo', 'note', 'createdAt', 'updatedAt'],
  PayrollSlip: ['id', 'companyId', 'employeeId', 'period', 'baseSalary', 'allowances', 'overtimeHours', 'overtimePay', 'bonus', 'deductions', 'insurance', 'tax', 'netPay', 'status', 'paidAt', 'note', 'createdAt', 'updatedAt', 'journalEntryId', 'paymentMethod', 'leaveDays', 'absentDays'],
  PerformanceReview: ['id', 'companyId', 'employeeId', 'period', 'score', 'strengths', 'weaknesses', 'reviewerName', 'suggestedBonus', 'note', 'createdAt', 'updatedAt'],
  PosTerminal: ['id', 'companyId', 'terminalNo', 'serialNo', 'merchantId', 'bankName', 'pspName', 'type', 'status', 'accountNo', 'iban', 'holderName', 'location', 'simNumber', 'cashBoxId', 'installedAt', 'note', 'createdAt', 'updatedAt'],
  PriceLevel: ['id', 'companyId', 'name', 'description', 'isDefault', 'createdAt'],
  Product: ['id', 'companyId', 'categoryId', 'name', 'sku', 'barcode', 'description', 'purchasePrice', 'salePrice', 'taxRate', 'unit', 'status', 'trackInventory', 'minStock', 'expiryDate', 'isWeighed', 'scaleCode', 'isRationEligible', 'rationPrice', 'createdAt', 'updatedAt', 'isOnline', 'onlinePrice', 'imageUrl'],
  ProductPrice: ['id', 'priceLevelId', 'productId', 'price', 'createdAt', 'companyId', 'minQty', 'updatedAt'],
  ProductReturn: ['id', 'companyId', 'returnNo', 'saleId', 'customerId', 'reason', 'status', 'totalAmount', 'note', 'createdAt', 'updatedAt', 'type', 'purchaseId', 'supplierId', 'warehouseId', 'refundMethod', 'refundAmount', 'cashBoxId', 'userId', 'appliedAt'],
  ProductReturnItem: ['id', 'returnId', 'productId', 'name', 'qty', 'unitPrice', 'total', 'sourceItemId'],
  ProductVariant: ['id', 'productId', 'name', 'sku', 'barcode', 'price', 'createdAt', 'updatedAt'],
  Project: ['id', 'companyId', 'projectNo', 'title', 'clientName', 'budget', 'startDate', 'endDate', 'status', 'progress', 'description', 'createdAt', 'updatedAt'],
  ProjectTask: ['id', 'projectId', 'title', 'assigneeId', 'status', 'priority', 'dueDate', 'estimatedHours', 'description', 'createdAt', 'updatedAt'],
  PropertyAudit: ['id', 'companyId', 'auditNo', 'ownerName', 'address', 'areaSqm', 'zone', 'annualTax', 'lastAuditYear', 'isPaid', 'note', 'createdAt', 'updatedAt'],
  Purchase: ['id', 'companyId', 'supplierId', 'warehouseId', 'purchaseNo', 'status', 'subtotal', 'discount', 'tax', 'total', 'note', 'createdAt', 'updatedAt', 'freightCost', 'freightCarrier', 'capitalizeFreight'],
  PurchaseItem: ['id', 'purchaseId', 'productId', 'quantity', 'purchasePrice', 'total', 'createdAt', 'returnedQty', 'batchNo', 'expiryDate', 'manufactureDate', 'freightShare', 'landedUnitCost'],
  Quotation: ['id', 'companyId', 'quoteNo', 'customerId', 'validUntil', 'status', 'totalAmount', 'discount', 'tax', 'note', 'salesOrderId', 'createdAt', 'updatedAt'],
  QuotationItem: ['id', 'quotationId', 'productId', 'name', 'qty', 'unitPrice', 'total'],
  PurchaseInquiry: ['id', 'companyId', 'inquiryNo', 'title', 'status', 'warehouseId', 'note', 'purchaseId', 'createdBy', 'createdAt', 'updatedAt'],
  PurchaseInquiryItem: ['id', 'inquiryId', 'productId', 'qty', 'lastPrice'],
  SupplierCall: ['id', 'companyId', 'inquiryId', 'supplierId', 'status', 'channel', 'phone', 'providerId', 'recordingUrl', 'transcript', 'durationSec', 'error', 'note', 'calledAt', 'createdAt', 'updatedAt'],
  SupplierQuote: ['id', 'companyId', 'callId', 'productId', 'unitPrice', 'availableQty', 'leadDays', 'note', 'isSelected', 'createdAt'],
  SupportSession: ['id', 'companyId', 'code', 'scope', 'grantedBy', 'reason', 'expiresAt', 'usedAt', 'revokedAt', 'supportName', 'createdAt'],
  TaxInvoice: ['id', 'companyId', 'saleId', 'taxId', 'status', 'referenceNo', 'attempts', 'lastError', 'payload', 'sentAt', 'confirmedAt', 'createdAt', 'updatedAt'],
  TaxInvoiceLog: ['id', 'companyId', 'taxInvoiceId', 'action', 'httpStatus', 'response', 'createdAt'],
  TaxSetting: ['companyId', 'memoryId', 'economicCode', 'apiBaseUrl', 'privateKeyPem', 'clientId', 'serial', 'isEnabled', 'isSandbox', 'createdAt', 'updatedAt'],
  VoicePhrase: ['id', 'companyId', 'lang', 'dialect', 'kind', 'productId', 'textFa', 'textTarget', 'sortOrder', 'createdAt'],
  VoiceSample: ['id', 'companyId', 'phraseId', 'audioUrl', 'durationMs', 'sizeBytes', 'speakerTag', 'status', 'rejectReason', 'recordedBy', 'createdAt'],
  VoipSetting: ['companyId', 'provider', 'isEnabled', 'callerId', 'apiKey', 'webhookSecret', 'maxCallsPerRun', 'createdAt', 'updatedAt'],
  QuickKeyGroup: ['id', 'companyId', 'name', 'color', 'sortOrder', 'isActive', 'createdAt', 'updatedAt'],
  QuickKey: ['id', 'companyId', 'groupId', 'productId', 'label', 'color', 'defaultQty', 'sortOrder', 'createdAt', 'updatedAt'],
  RationAccount: ['id', 'companyId', 'nationalCode', 'holderName', 'phone', 'householdSize', 'balance', 'periodCode', 'isActive', 'note', 'createdAt', 'updatedAt'],
  RationTransaction: ['id', 'companyId', 'accountId', 'type', 'amount', 'saleId', 'periodCode', 'reference', 'note', 'createdAt'],
  Receipt: ['id', 'companyId', 'receiptNo', 'entityType', 'entityId', 'amount', 'method', 'cashBoxId', 'treasuryAccountId', 'payerName', 'reference', 'note', 'paidAt', 'createdAt'],
  RestaurantArea: ['id', 'companyId', 'name', 'floor', 'isSmoking', 'isOutdoor', 'isActive', 'createdAt', 'updatedAt'],
  RestaurantOrder: ['id', 'companyId', 'orderNo', 'type', 'status', 'tableId', 'customerId', 'waiterId', 'guestCount', 'subtotal', 'discount', 'serviceCharge', 'tax', 'total', 'paidAmount', 'tipAmount', 'paymentMethod', 'deliveryAddress', 'deliveryPhone', 'deliveryFee', 'courierName', 'saleId', 'note', 'openedAt', 'kitchenAt', 'closedAt', 'createdAt', 'updatedAt'],
  RestaurantOrderItem: ['id', 'orderId', 'menuItemId', 'name', 'qty', 'unitPrice', 'discount', 'total', 'status', 'station', 'note', 'sentAt', 'readyAt', 'servedAt', 'createdAt'],
  RestaurantShift: ['id', 'companyId', 'userId', 'startedAt', 'endedAt', 'openingCash', 'closingCash', 'totalSales', 'tipsAmount', 'ordersCount', 'note', 'createdAt'],
  RestaurantTable: ['id', 'companyId', 'areaId', 'tableNo', 'capacity', 'status', 'qrCode', 'note', 'createdAt', 'updatedAt'],
  SafetyInspection: ['id', 'companyId', 'propertyName', 'address', 'ownerName', 'ownerPhone', 'result', 'certificateNo', 'validUntil', 'notes', 'inspectedAt', 'createdAt', 'updatedAt'],
  Sale: ['id', 'companyId', 'customerId', 'userId', 'warehouseId', 'invoiceNo', 'status', 'subtotal', 'discount', 'tax', 'total', 'note', 'createdAt', 'updatedAt', 'shiftId', 'rationAccountId', 'rationAmount', 'salesAgentId', 'freightCharge', 'freightCost', 'discountCodeId', 'taxInvoiceId', 'discountBy', 'reference', 'dueDate', 'additions', 'deductions', 'invoiceDate', 'agentCommission'],
  SaleItem: ['id', 'saleId', 'productId', 'quantity', 'price', 'discount', 'total', 'createdAt', 'returnedQty', 'manualDiscount', 'note', 'taxRate', 'taxAmount', 'serial'],
  StockCount: ['id', 'companyId', 'warehouseId', 'countNo', 'status', 'note', 'userId', 'appliedAt', 'createdAt', 'updatedAt'],
  StockCountLine: ['id', 'countId', 'productId', 'systemQty', 'countedQty', 'note'],
  StockMovement: ['id', 'companyId', 'warehouseId', 'productId', 'delta', 'balance', 'reason', 'refType', 'refId', 'userId', 'note', 'createdAt'],
  AgentCommission: ['id', 'companyId', 'agentId', 'period', 'salesTotal', 'returnTotal', 'netSales', 'rate', 'amount', 'invoiceCount', 'status', 'paidAt', 'note', 'createdAt', 'updatedAt'],
  SalesAgent: ['id', 'companyId', 'name', 'phone', 'territory', 'commissionRate', 'monthlyTarget', 'isActive', 'createdAt', 'updatedAt', 'agentNo', 'userId', 'nationalCode'],
  SalesOrder: ['id', 'companyId', 'orderNo', 'customerId', 'quotationId', 'saleId', 'warehouseId', 'status', 'totalAmount', 'discount', 'tax', 'note', 'createdAt', 'updatedAt'],
  SalesOrderItem: ['id', 'orderId', 'productId', 'name', 'qty', 'unitPrice', 'total', 'shippedQty'],
  SensorAlert: ['id', 'sensorId', 'value', 'message', 'isRead', 'createdAt'],
  SensorReading: ['id', 'sensorId', 'value', 'unit', 'recordedAt'],
  SerialNumber: ['id', 'companyId', 'productId', 'serial', 'status', 'saleId', 'warrantyUntil', 'note', 'createdAt', 'updatedAt'],
  ServiceZone: ['id', 'companyId', 'name', 'kind', 'areaSqm', 'contractorName', 'schedule', 'monthlyCost', 'isActive', 'createdAt', 'updatedAt'],
  Shipment: ['id', 'companyId', 'trackingNo', 'saleId', 'carrier', 'method', 'fee', 'estimatedAt', 'deliveredAt', 'status', 'address', 'note', 'createdAt', 'updatedAt', 'salesOrderId', 'carrierCost', 'journalEntryId'],
  ShipmentItem: ['id', 'shipmentId', 'productId', 'name', 'qty'],
  StreetLight: ['id', 'companyId', 'lightCode', 'address', 'zone', 'lightType', 'installDate', 'status', 'createdAt', 'updatedAt'],
  StreetLightReport: ['id', 'lightId', 'reportDate', 'fault', 'isDone', 'fixedAt', 'createdAt'],
  SmsMessage: ['id', 'companyId', 'phone', 'customerId', 'body', 'status', 'skipReason', 'error', 'providerId', 'cost', 'kind', 'campaignId', 'dedupeKey', 'sentAt', 'createdAt'],
  SmsTemplate: ['id', 'companyId', 'name', 'body', 'isActive', 'createdAt', 'updatedAt'],
  Supplier: ['id', 'companyId', 'name', 'phone', 'email', 'address', 'isActive', 'createdAt', 'updatedAt'],
  Survey: ['id', 'companyId', 'title', 'description', 'isActive', 'createdAt', 'updatedAt'],
  SurveyAnswer: ['id', 'questionId', 'responseId', 'value'],
  SurveyQuestion: ['id', 'surveyId', 'text', 'qtype', 'options', 'sortOrder'],
  SurveyResponse: ['id', 'surveyId', 'respondentName', 'submittedAt'],
  TableReservation: ['id', 'companyId', 'tableId', 'customerName', 'phone', 'guests', 'reservedAt', 'durationMin', 'status', 'note', 'createdAt', 'updatedAt'],
  TaxiDriver: ['id', 'companyId', 'licenseNo', 'firstName', 'lastName', 'phone', 'plateNo', 'vehicleModel', 'licenseExpiry', 'status', 'createdAt', 'updatedAt'],
  TaxiViolation: ['id', 'driverId', 'date', 'description', 'fine', 'isPaid', 'createdAt'],
  TechnicalInspection: ['id', 'permitId', 'inspectorName', 'result', 'notes', 'inspectedAt', 'createdAt'],
  Tender: ['id', 'companyId', 'tenderNo', 'title', 'kind', 'baseAmount', 'deadline', 'status', 'winnerBidId', 'description', 'createdAt', 'updatedAt'],
  TenderBid: ['id', 'tenderId', 'bidderName', 'bidderPhone', 'amount', 'notes', 'createdAt'],
  TicketMessage: ['id', 'ticketId', 'body', 'isAgent', 'senderName', 'createdAt'],
  TimeEntry: ['id', 'projectId', 'companyId', 'employeeId', 'date', 'hours', 'description', 'createdAt'],
  TrainingCourse: ['id', 'companyId', 'title', 'instructor', 'hours', 'startDate', 'endDate', 'isActive', 'createdAt', 'updatedAt'],
  TrainingEnrollment: ['id', 'courseId', 'employeeId', 'score', 'passed', 'certUrl', 'createdAt'],
  TreasuryAccount: ['id', 'companyId', 'name', 'type', 'bankName', 'accountNo', 'iban', 'balance', 'isActive', 'note', 'createdAt', 'updatedAt'],
  TreasuryTransaction: ['id', 'companyId', 'accountId', 'type', 'amount', 'reference', 'description', 'date', 'createdAt'],
  User: ['id', 'firstName', 'lastName', 'email', 'phone', 'password', 'role', 'status', 'avatar', 'companyId', 'createdAt', 'updatedAt'],
  UtilityBill: ['id', 'meterId', 'period', 'usage', 'amount', 'isPaid', 'paidAt', 'createdAt'],
  UtilityMeter: ['id', 'companyId', 'meterNo', 'kind', 'address', 'ownerName', 'createdAt', 'updatedAt'],
  UtilityReading: ['id', 'meterId', 'readDate', 'value', 'reader', 'createdAt'],
  Warehouse: ['id', 'companyId', 'branchId', 'name', 'code', 'description', 'createdAt', 'updatedAt'],
  Webhook: ['id', 'companyId', 'name', 'kind', 'url', 'secret', 'isActive', 'createdAt', 'updatedAt'],
  WebhookLog: ['id', 'webhookId', 'payload', 'status', 'sentAt'],
  ZoneWorkLog: ['id', 'zoneId', 'date', 'description', 'isDone', 'createdAt'],
};
